# Generated by Django 2.0.1 on 2019-02-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gadv',
            field=models.BooleanField(default=False, verbose_name='商品推荐'),
        ),
    ]
